[pytest]
pythonpath=.
python_files=test_*
python_classes=Test*
python_functions=test_*
markers = 
    slow: Slow running tests
    validation: Replication of a published case study, run on request only
